spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db.url-port}/jstart_ai_agent?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: ${db.username}
    password: ${db.password}
  application:
    name: jstart-ai-agent
  profiles:
    active: local # 设置为 local 环境
  ai:
    dashscope:
      api-key: ${ai.dashscope.api-key} # 读取local环境中的api-key
      chat:
        options:
          model: qwen-plus-2025-01-25

server:
  port: 8123
  servlet:
    context-path: /api

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.qianyv.jstartaiagent.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

search-api:
  api-key: ${my-search-api-key} # 替换为实际的搜索API密钥，申请地址：https://www.searchapi.io/

